baseurl: /
languageCode: en-us
defaultContentLanguage: en
title: Okkur - Syna
theme: syna-innovar
enableGitInfo: yes
version: 0.17.4
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
ignorefiles: content/dev/.*
googleAnalytics: ''
outputs:
  home:
    - HTML
    - JSON
frontmatter:
  date:
    - date
    - lastmod
  lastmod:
    - lastmod
    - :git
    - date
markup:
  goldmark:
    renderer:
      unsafe: yes
params:
  analytics:
    piwik: {}
  colors:
    danger: '#dc1200'
    dark: '#343a40'
    info: '#00c9dc'
    light: '#f8f9fa'
    primary: '#00838F'
    secondary: '#868e96'
    success: '#008f54'
    warning: '#fdf314'
  custom:
    favicon: favicon.ico
    favicon_ico_sizes: 16x16 32x32
    favicon_png: favicon.png
    favicon_svg: favicon.svg
  debug: yes
  description: Open Source Theme for your next project
  fontawesome:
    disabled: no
    pro: no
  name: Okkur Labs
  style: {}
  unsafeEvents: yes
menu:
  copyright_footer:
    - name: About Us
      url: /about
      weight: 10
  footer:
    - name: Acerca de InnovaLab
      url: https://www.innovalab.info/
      weight: 10
    - name: Página de Notion
      url: https://www.notion.so/innovalab/InnovaLab-8ff7c0bbb9c2465ca6f9e0f7436f6a8c
      weight: 20
  footer_social:
    - name: github
      pre: fab fa-github fa-stack-2x
      url: https://github.com/healthinnovation
      weight: 30
  main:
    - name: Inicio
      url: /
      weight: 10
    - name: Syllabus
      url: /docs
      weight: 20
    - name: Contenido
      url: /fragments
      weight: 30
    - name: Extras
      url: /about
      weight: 40
